name: 'Run a recheck'
description: 'Runs a reverse dependency check similar to CRAN'
inputs:
  package:
    description: 'Path or URL to source package tarball'
    required: true
  which:
    description: 'Should be strong or most'
    default: strong
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/recheck'
  args:
    - ${{ inputs.package }}
    - ${{ inputs.which }}
