name: 'Run a recheck'
description: 'Runs a reverse dependency check similar to CRAN'
inputs:
  package:
    description: 'Path or URL to source package tarball'
    required: true
  universe:
    description: 'Which universe to check in'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/recheck'
  args:
    - ${{ inputs.package }}
