name: Test a recheck

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to a source package tarball'
        required: true

jobs:
  recheck:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Free some disk space
        run: rm -Rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
      - name: Test recheck
        uses: r-universe-org/recheck@HEAD
        with:
          package: ${{ github.event.inputs.package_url }}
      - uses: actions/upload-artifact@v4
        with:
          name: checklogs
          path: |
            */*.log
            */*.out
            */*.Rout
            */*.fail
            check-details.*
