name: Test a recheck

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to a source package tarball'
        required: true

jobs:
  recheck:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Test recheck
        uses: r-universe-org/recheck@HEAD
        with:
          package: ${{ github.event.inputs.package_url }}
