name: Test a recheck

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to a source package tarball'
        required: true
      which:
        type: choice
        description: Which reverse dependencies to check
        options:
        - strong
        - most

jobs:
  recheck:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Free some disk space
        if: runner.os == 'linux'
        run: rm -Rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
      - name: Test recheck
        uses: r-universe-org/recheck@HEAD
        with:
          package: ${{ github.event.inputs.package_url }}
          which: ${{ github.event.inputs.which }}
      - uses: actions/upload-artifact@v4
        with:
          name: checklogs
          path: |
            */*.log
            */*.out
            */*.Rout
            */*.fail
            check-details.*
